# permissions for end users to view postgressnapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: postgressnapshot-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cloud-resource-operator
    app.kubernetes.io/part-of: cloud-resource-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgressnapshot-viewer-role
rules:
- apiGroups:
  - integreatly.org
  resources:
  - postgressnapshots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - integreatly.org
  resources:
  - postgressnapshots/status
  verbs:
  - get
