# permissions for end users to edit blobstorages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: blobstorage-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cloud-resource-operator
    app.kubernetes.io/part-of: cloud-resource-operator
    app.kubernetes.io/managed-by: kustomize
  name: blobstorage-editor-role
rules:
- apiGroups:
  - integreatly.org
  resources:
  - blobstorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integreatly.org
  resources:
  - blobstorages/status
  verbs:
  - get
