---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumes
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - infrastructures
  - networks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - integreatly.org
  resources:
  - blobstorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integreatly.org
  resources:
  - blobstorages/finalizers
  verbs:
  - update
- apiGroups:
  - integreatly.org
  resources:
  - blobstorages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - integreatly.org
  resources:
  - postgres
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integreatly.org
  resources:
  - postgres
  - postgressnapshots
  - redis
  - redissnapshots
  verbs:
  - list
  - watch
- apiGroups:
  - integreatly.org
  resources:
  - postgres/finalizers
  verbs:
  - update
- apiGroups:
  - integreatly.org
  resources:
  - postgres/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - integreatly.org
  resources:
  - postgressnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integreatly.org
  resources:
  - postgressnapshots/finalizers
  verbs:
  - update
- apiGroups:
  - integreatly.org
  resources:
  - postgressnapshots/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - integreatly.org
  resources:
  - redis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integreatly.org
  resources:
  - redis/finalizers
  verbs:
  - update
- apiGroups:
  - integreatly.org
  resources:
  - redis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - integreatly.org
  resources:
  - redissnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integreatly.org
  resources:
  - redissnapshots/finalizers
  verbs:
  - update
- apiGroups:
  - integreatly.org
  resources:
  - redissnapshots/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: cloud-resource-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - persistentvolumeclaims
  - pods
  - pods/exec
  - secrets
  - services
  - services/finalizers
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - cloud-resource-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - cloudcredential.openshift.io
  resources:
  - credentialsrequests
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - '*'
  - authentications
  - builds
  - clusteroperators
  - featuregates
  - infrastructures
  - ingresses
  - networks
  - schedulers
  verbs:
  - '*'
- apiGroups:
  - integreatly
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - integreatly.org
  resources:
  - '*'
  - postgres
  - postgressnapshots
  - redis
  - redissnapshots
  - smtpcredentialset
  verbs:
  - '*'
- apiGroups:
  - integreatly.org
  resources:
  - blobstorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integreatly.org
  resources:
  - blobstorages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - get
- apiGroups:
  - operators.coreos.com
  resources:
  - catalogsources
  verbs:
  - get
  - patch
  - update
