apiVersion: integreatly.integreatly.org/v1alpha1
kind: Postgres
metadata:
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres-sample
    app.kubernetes.io/part-of: cloud-resource-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cloud-resource-operator
  name: postgres-sample
spec:
  # TODO(user): Add fields here
